apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-operator-depl
  namespace: poc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-operator-app
  template:
    metadata:
      labels:
        app: poc-operator-app
    spec:
      serviceAccountName: operator-sa
      containers:
        - name: poc-operator-container
          image: poc-operator:latest
          imagePullPolicy: Never
          env:
            - name: DEPLOYMENT
              value: "hello-depl"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-depl
  namespace: poc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-container
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args: ["while true; do echo 'Hello, world!'; sleep 10; done"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa
  namespace: poc-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-role
  namespace: poc-operator
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-role-binding
  namespace: poc-operator
subjects:
  - kind: ServiceAccount
    name: operator-sa
    namespace: poc-operator
roleRef:
  kind: Role
  name: operator-role
  apiGroup: rbac.authorization.k8s.io
